Repository o3de/o3de.org, pull requests merged in 2022-05, with the labels that each got.

#1473 Updated PhysX Wind Provider topic. Updated steps moved/replaced images.
  content/docs/learning-guide/tutorials/_index.md
  content/docs/learning-guide/tutorials/physx/_index.md
  content/docs/learning-guide/tutorials/physx/wind-provider.md
  content/docs/user-guide/components/reference/physx/cloth.md
  content/docs/user-guide/interactivity/physics/nvidia-physx/_index.md
  content/docs/user-guide/interactivity/physics/nvidia-physx/configuring/configuration-global.md
  content/docs/user-guide/interactivity/physics/nvidia-physx/wind-provider.md
  static/images/learning-guide/tutorials/physx/cloth-simulate-in-editor.png
  static/images/learning-guide/tutorials/physx/disable-local-wind-velocity.png
  static/images/learning-guide/tutorials/physx/edit-cloth-locked-edge-prefab.png
  static/images/learning-guide/tutorials/physx/wind-collider-setup.png
  static/images/learning-guide/tutorials/physx/wind-configuration.png
  static/images/learning-guide/tutorials/physx/wind-force-region-setup.png
  static/images/learning-guide/tutorials/physx/wind-provider-cloth-prefab.png
  static/images/learning-guide/tutorials/physx/wind-simulation-result.mp4
  static/images/learning-guide/tutorials/physx/wind-tag-setup.png
  static/images/user-guide/physx/physx/anim-wind-example.gif
  static/images/user-guide/physx/physx/ui-physx-wind-cloth-entity.png
  static/images/user-guide/physx/physx/ui-physx-wind-configuration.png
  static/images/user-guide/physx/physx/ui-physx-wind-entity.png
Labels: priority/critical

#1569 Document all Networking and network adjancent console variables and settings
  content/docs/user-guide/appendix/cvars/_index.md
  content/docs/user-guide/networking/_index.md
  content/docs/user-guide/networking/settings.md
Labels: feature/networking, sig/network

#1536 Move lost page PBR Reference Materials Gem
  content/docs/user-guide/gems/reference/rendering/pbr-reference-materials.md
Labels: size/XS

#1534 Author deferred fog component reference page
  content/docs/user-guide/components/reference/atom/deferred-fog.md
  static/images/user-guide/components/reference/atom/deferred-fog/basic-example.png
  static/images/user-guide/components/reference/atom/deferred-fog/deferred-fog-component-ui.png
Labels: priority/minor, sig/graphics-audio, status/needs-edit

#1494 Component development section update
  content/docs/user-guide/programming/components/_index.md
  content/docs/user-guide/programming/components/create-component.md
  content/docs/user-guide/programming/components/editor-components.md
  content/docs/user-guide/programming/components/overview.md
  content/docs/user-guide/programming/components/reflection/reflecting-for-serialization.md
  content/docs/user-guide/programming/components/reflection/serialization-context/_index.md
  content/docs/user-guide/programming/components/reflection/serialization-context/versioning.md
  content/docs/user-guide/programming/components/services.md
  content/docs/user-guide/programming/components/system-components.md
Labels: priority/critical

#1626 Add new favicon, logos and media assets for the release of for 22.05.0
  assets/sass/custom.sass
  layouts/partials/download/content-linux.html
  layouts/partials/download/content-windows.html
  static/apple-touch-icon-114x114.png
  static/apple-touch-icon-120x120.png
  static/apple-touch-icon-144x144.png
  static/apple-touch-icon-152x152.png
  static/apple-touch-icon-180x180.png
  static/apple-touch-icon-57x57.png
  static/apple-touch-icon-72x72.png
  static/apple-touch-icon-76x76.png
  static/apple-touch-icon.png
  static/favicon.ico
  static/images/api-reference/api-ref-icon.png
  static/images/blog/announcement_thumbnail.jpg
  static/images/tools-ui/branding-guidelines/bjds-banner.png
  static/images/tools-ui/branding-guidelines/brand-guideline.png
  static/images/tools-ui/branding-guidelines/logo-files.png
  static/images/tools-ui/branding-guidelines/page-banner.png
  static/images/tools-ui/icons-component.png
  static/images/welcome-guide/desktop-icon-editor.png
  static/images/welcome-guide/wg-welcome-page-color.png
  static/img/home/video-thumbnail-about-o3de.jpg
  static/img/home/video-thumbnail-atom-renderer.jpg
  static/img/home/video-thumbnail-aws-gems.jpg
  static/img/home/video-thumbnail-creating-projects-using-command-line.jpg
  static/img/home/video-thumbnail-developer-overview.jpg
  static/img/home/video-thumbnail-networking-overview.jpg
  static/img/home/video-thumbnail-o3de-editor-tour.jpg
  static/img/home/video-thumbnail-script-canvas-overview.jpg
  static/img/home/video-thumbnail-setting-up-o3de-from-github.jpg
  static/img/home/video-thumbnail-what-is-o3de.jpg
  static/img/logos/O3DE-Circle-Icon-REV-MONO.svg
  static/img/logos/O3DE-Circle-Icon-REV.svg
  static/img/logos/O3DE-Circle-Icon.png
  static/img/logos/O3DE-Circle-Icon.svg
  static/img/logos/O3DE-Circle-LogoMark-REV-MONO.svg
  static/img/logos/O3DE-Circle-LogoMark-REV.svg
  static/img/logos/O3DE-Logo-Black-Mono.svg
  static/img/logos/O3DE-Logo-REV-Mono.svg
  static/img/logos/O3DE-Logo-with-WordMark-Black-Mono.svg
  static/img/logos/O3DE-Logo-with-WordMark-REV-Mono.svg
  static/img/logos/O3DECon_Logo-White.svg
  static/img/logos/O3DEJam_Logo-REV-COLOR.svg
Labels: do-not-merge/hold

#1631 Removing the word stable from download pages per release call.
  layouts/partials/download/content-linux.html
  layouts/partials/download/content-windows.html
Labels: priority/critical

#1594 Update instructions for setting up AtomSampleViewer. Remove AtomTest …
  content/docs/atom-guide/setup-atom-projects.md
  static/images/atom-guide/atom-sample-viewer/shadow.png
Labels: priority/major

#1640 Fixed a typo in the motion matching blog post
  content/blog/posts/o3de-motion-matching-2022-04.md
Labels: feature/animation, kind/website, sig/simulation

#1638 Update smoketest image-width example
  content/smoketest.md
Labels: size/XS

#1625 Updated instructions to setup Hugo
  README.md
  content/docs/contributing/to-docs/o3de-docs-repo-setup.md
Labels: priority/major, status/needs-edit

#1608 Fix broken link: user-guide/_index
  content/docs/user-guide/_index.md
Labels: size/XS

#1613 Media updates: interactivity/user-interface
  content/docs/user-guide/interactivity/user-interface/elements/_index.md
  static/images/user-guide/interactivity/user-interface/canvases/ui-editor-creating-canvases-1.png
  static/images/user-guide/interactivity/user-interface/elements/ui-editor-elements.png
Labels: size/XS

#1479 Separated Source and Job Dependencies. Added a note on the upcoming
  content/docs/user-guide/assets/pipeline/asset-dependencies-and-identifiers.md
Labels: do-not-merge/work-in-progress

#1639 Material component documentation
  content/docs/user-guide/components/reference/_index.md
  content/docs/user-guide/components/reference/atom/material.md
  static/images/user-guide/components/reference/atom/material/material-base-properties-ui.png
  static/images/user-guide/components/reference/atom/material/material-extended-slot-properties-ui.png
  static/images/user-guide/components/reference/atom/material/material-generate-ui.png
  static/images/user-guide/components/reference/atom/material/material-inspector-ui.png
  static/images/user-guide/components/reference/atom/material/material-menu-ui.png
  static/images/user-guide/components/reference/atom/material/material-slot-menu-ui.png
  static/images/user-guide/components/reference/atom/material/material-slot-properties-ui.png
Labels: status/needs-edit

#1680 Add editorsv_rhi_override CVAR to Multiplayer testing page
  content/docs/user-guide/gems/reference/multiplayer/multiplayer-gem/test-in-editor.md
Labels: sig/network
