Repository o3de/o3de.org, pull requests merged in 2022-04, with the labels that each got.

#1527 Fix broken links - GHI 1406, 1407, 1422, 1445
  content/docs/atom-guide/look-dev/color-management/index.md
  content/docs/atom-guide/look-dev/textures/_index.md
  content/docs/user-guide/programming/gems/_index.md
  content/docs/user-guide/programming/gems/manifest.md
  content/docs/user-guide/project-config/register-gems.md
Labels: size/XS

#1517 Add multiplayer spawner docs
  content/docs/user-guide/gems/reference/multiplayer/_index.md
  content/docs/user-guide/gems/reference/multiplayer/multiplayer-gem/spawning.md
Labels: sig/network

#1537 Add entity reference doc.
  content/docs/user-guide/components/reference/atom/entity-reference.md
  static/images/user-guide/components/reference/atom/entity-reference-ui.png
Labels: sig/graphics-audio

#1538 Added HDR Color Grading doc.
  content/docs/user-guide/components/reference/atom/hdr-color-grading.md
  static/images/user-guide/components/reference/atom/post-processing-modifiers/hdr-color-grading/hdr-color-grading-activate-lut-ui.png
  static/images/user-guide/components/reference/atom/post-processing-modifiers/hdr-color-grading/hdr-color-grading-component-channel-mixing-ui.png
  static/images/user-guide/components/reference/atom/post-processing-modifiers/hdr-color-grading/hdr-color-grading-component-color-adjustment-ui.png
  static/images/user-guide/components/reference/atom/post-processing-modifiers/hdr-color-grading/hdr-color-grading-component-final-adjustment-ui.png
  static/images/user-guide/components/reference/atom/post-processing-modifiers/hdr-color-grading/hdr-color-grading-component-lut-generation-ui.png
  static/images/user-guide/components/reference/atom/post-processing-modifiers/hdr-color-grading/hdr-color-grading-component-shadow-midtones-higlights-ui.png
  static/images/user-guide/components/reference/atom/post-processing-modifiers/hdr-color-grading/hdr-color-grading-component-split-toning-ui.png
  static/images/user-guide/components/reference/atom/post-processing-modifiers/hdr-color-grading/hdr-color-grading-component-white-balance-ui.png
  static/images/user-guide/components/reference/atom/post-processing-modifiers/hdr-color-grading/hdr-color-grading-generate-lut-ui.png
Labels: sig/graphics-audio

#1541 Update docs showing audio requests code
  content/docs/user-guide/interactivity/audio/advanced-topics/audio-panning-mode.md
  content/docs/user-guide/interactivity/audio/advanced-topics/sound-duration-runtime.md
  content/docs/user-guide/interactivity/audio/console-variables.md
Labels: sig/graphics-audio
